# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Dom Ceja
tagline:             'Journey of a Software Engineer'
description:         'Spreading knowledge one byte at a time'
url:                 http://blog.ceja.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dominique Ceja
  url:               https://github.com/domceja
  email:             hello@ceja.io

# Custom vars
version:             1.0.0

# Gems
gems:                 [jekyll-paginate]

# Blog post comments
disqus_shortname:        blogceja