# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Dom Ceja
tagline:             'Journey of a Software Engineer'
description:         'Spreading knowledge one byte at a time'
url:                 http://blog.ceja.io
baseurl:             ''
paginate:            5
github:             https://github.com/domceja
linkdin:            https://www.linkedin.com/in/dominiqueceja/
codepen:            https://codepen.io/domceja/
google_analytics:   'UA-91013896-1'

# About/contact
author:
  name:              Dominique Ceja
  url:               https://github.com/domceja
  email:             hello@ceja.io

# Custom vars
version:             0.1.0

# Gems
gems:                 [jekyll-paginate]

# Blog post comments
disqus_shortname:        blogceja